version: '3.8'

services:
  band-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Set this to your Supabase Postgres DSN in env or compose override
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./config:/app/config:ro
      - band_uploads:/app/uploads
    restart: unless-stopped

volumes:
  band_uploads: